# ¿Deseas contribuir en el libro? {#contribute}

Gracias por leer nuestro libro de Data Science.
El libro se encuentra bajo constante desarrollo, por lo que conforme pase el tiempo más capítulos y ejemplos, serán añadidos.

El texto se encuentra disponible para comentarios específicos en
[github.com](https://github.com/arturochian/DSFA).
En la página de github puedes crear [issues](https://github.com/arturochian/DSFA/issues) si encuentras un error o un detalle específico por mejorar.

Si deseas apoyar en el avance del libro, y no manejas mucho github, puedes escribirme un correo a [arturob.chian@gmail.com](mailto:arturob.chian).



# Citando este libro {#cite}

Si encuentras útil este libro, agradeceré citar el documento de la siguiente forma

    Chian, Arturo. "Data Science con R: Fundamentos y Aplicaciones", 2019. https://bookdown.org/BEST/DSFA/.

O usando bibtex:


    @book{chian,
      title      = {Data Science con R: Fundamentos y Aplicaciones},
      author     = {Arturo Chian},
      publisher  = {https://bookdown.org/BEST/DSFA/},
      note       = {\url{https://bookdown.org/BEST/DSFA/}},
      year       = {2019}
    }


